name: fallingStars
version: 0.1.0.0

dependencies:
- base >= 4.14 && < 5
- gloss
- random
- OpenGL
- GLUT
- array
- GLFW-b
- mtl
- vector
- JuicyPixels

executables:
  fallingStars:
    main: fallingStars.hs
    source-dirs: .
  sponge:
    main: sponge.hs
    source-dirs: .
  snake:
    main: snake.hs
    source-dirs: .
  carpet:
    main: carpet.hs
    source-dirs: .
  triangle:
    main: triangle.hs
    source-dirs: .
  pyramid:
    main: pyramid.hs
    source-dirs: .
  balls:
    main: bouncingBalls.hs
    source-dirs: .
  ellipsoid:
    main: ellipsoid.hs
    source-dirs: .
  gravity:
    main: gravity.hs
    source-dirs: .
  fourier:
    main: fourier.hs
    source-dirs: .
